name: Dry run poetry publish

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - 'main'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Publish to pypi
      uses: coveooss/pypi-publish-with-poetry@v0.1.3
      with:
        project-name: EasyECS
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        dry-run: true
